import {OrderType} from '@/app/views/ecommerce/orders/types';

export const orders: OrderType[] = [
    {
        id: 'WB20100',
        date: '9 May, 2025',
        time: '10:10 AM',
        name: 'Mason Carter',
        avatar: 'assets/images/users/user-2.jpg',
        email: 'mason.carter@shopmail.com',
        amount: 129.45,
        paymentStatus: 'paid',
        orderStatus: 'delivered',
        cardImage: 'assets/images/cards/visa.svg',
        cardNumber: 'xxxx 7832',
    },
    {
        id: 'WB20101',
        date: '7 May, 2025',
        time: '11:45 AM',
        name: 'Ava Martin',
        avatar: 'assets/images/users/user-9.jpg',
        email: 'ava.martin@marketplace.com',
        amount: 87.00,
        paymentStatus: 'pending',
        orderStatus: 'processing',
        cardImage: 'assets/images/cards/mastercard.svg',
        cardNumber: 'xxxx 5487',
    },
    {
        id: 'WB20102',
        date: '26 Apr, 2025',
        time: '1:20 PM',
        name: 'Noah Wilson',
        avatar: 'assets/images/users/user-1.jpg',
        email: 'noah.wilson@ecomsite.com',
        amount: 59.90,
        paymentStatus: 'failed',
        orderStatus: 'cancelled',
        cardImage: 'assets/images/cards/paypal.svg',
        cardNumber: 'xxxx 7832',
    },
    {
        id: 'WB20103',
        date: '27 Apr, 2025',
        time: '3:30 PM',
        name: 'Isabella Moore',
        avatar: 'assets/images/users/user-10.jpg',
        email: 'isabella.moore@onlineshop.com',
        amount: 215.20,
        paymentStatus: 'paid',
        orderStatus: 'shipped',
        cardImage: 'assets/images/cards/stripe.svg',
        cardNumber: 'xxxx 9901',
    },
    {
        id: 'WB20104',
        date: '28 Apr, 2025',
        time: '9:55 AM',
        name: 'Lucas Bennett',
        avatar: 'assets/images/users/user-5.jpg',
        email: 'lucas.bennett@shopzone.com',
        amount: 345.75,
        paymentStatus: 'paid',
        orderStatus: 'delivered',
        cardImage: 'assets/images/cards/american-express.svg',
        cardNumber: 'xxxx 4678',
    },
    {
        id: 'WB30100',
        date: '20 Apr, 2025',
        time: '2:30 PM',
        name: 'Emma Johnson',
        avatar: 'assets/images/users/user-3.jpg',
        email: 'emma.johnson@storemail.com',
        amount: 199.99,
        paymentStatus: 'paid',
        orderStatus: 'delivered',
        cardImage: 'assets/images/cards/discover-card.svg',
        cardNumber: 'xxxx 1234',
    },
    {
        id: 'WB30101',
        date: '21 Apr, 2025',
        time: '9:15 AM',
        name: 'Liam Thompson',
        avatar: 'assets/images/users/user-4.jpg',
        email: 'liam.thompson@buynow.com',
        amount: 75.50,
        paymentStatus: 'pending',
        orderStatus: 'processing',
        cardImage: 'assets/images/cards/unionpay.svg',
        cardNumber: 'xxxx 9876',
    },
    {
        id: 'WB30102',
        date: '22 Apr, 2025',
        time: '4:45 PM',
        name: 'Sophia Davis',
        avatar: 'assets/images/users/user-5.jpg',
        email: 'sophia.davis@shopsite.com',
        amount: 45.25,
        paymentStatus: 'failed',
        orderStatus: 'cancelled',
        cardImage: 'assets/images/cards/payoneer.svg',
        cardNumber: 'xxxx 7832',
    },
    {
        id: 'WB30103',
        date: '10 May, 2025',
        time: '11:00 AM',
        name: 'Oliver Brown',
        avatar: 'assets/images/users/user-6.jpg',
        email: 'oliver.brown@webstore.com',
        amount: 299.00,
        paymentStatus: 'paid',
        orderStatus: 'shipped',
        cardImage: 'assets/images/cards/google-wallet.svg',
        cardNumber: 'xxxx 9876',
    },
    {
        id: 'WB30104',
        date: '24 Apr, 2025',
        time: '8:20 AM',
        name: 'Charlotte Lee',
        avatar: 'assets/images/users/user-7.jpg',
        email: 'charlotte.lee@marketzone.com',
        amount: 420.80,
        paymentStatus: 'paid',
        orderStatus: 'delivered',
        cardImage: 'assets/images/cards/bhim.svg',
        cardNumber: 'xxxx 7832',
    }
];
